language: node_js

jobs:
  include:
    - stage: CI
      script: "Running unit tests here"
    - stage: Deploy to staging
      deploy: 
        provider: azure_web_apps
        site: $TRAVIS_APP_NAME_STAGING
    - stage: LaunchReady Testing
      script: "Script goes here"
    - stage: Deploy to production
      deploy: 
        provider: azure_web_apps
        site: $TRAVIS_APP_NAME_PRODUCTION
