language: node_js

jobs:
  include:
    - stage: Deploy to staging
      deploy: 
        provider: azure_web_apps
        site: $TRAVIS_APP_NAME_STAGING
    - stage: LaunchReady Testing
      script: build/travis-launchready.sh
    - stage: Deploy to production
      deploy: 
        provider: azure_web_apps
        site: $TRAVIS_APP_NAME_PRODUCTION
