version: 2
jobs:
  ci:
    working_directory: ~/app
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

#      - run:
#          name: Unit Tests
#          command: npm test

      - add-ssh-keys:
          fingerprints:
            - "81:c8:44:89:af:ef:08:f3:4b:a7:85:77:ae:38:bd:50"

      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME_STAGING.git HEAD:refs/heads/master
            heroku run python manage.py deploy
            heroku restart

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters: 
            branches:
              only: master
