version: 2
jobs:
  ci:
    working_directory: ~/app
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

#      - run:
#          name: Unit Tests
#          command: npm test

  deploy-staging:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - add-ssh-keys:
          fingerprints:
            - "81:c8:44:89:af:ef:08:f3:4b:a7:85:77:ae:38:bd:50"

      - run:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Heroku's fingerprint
              echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

              # Push changes
              git push --force git@heroku.com:$HEROKU_APP_NAME_STAGING.git HEAD:refs/heads/master
            fi
  
  test-staging:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      # Moved from individual run steps and external script because working directory is not a dir in checkout, it's a parent dir setting
      - run:
          name: LaunchReady Dependencies
          command: |
            cd build/launchready
            npm install

      - run:
          name: LaunchReady Testing
          command: |
            pwd
            cd build/launchready
            node build.js $LR_APPLICATIONID --appId=$LR_APPID --apiKey=$LR_APIKEY --name="CircleCI-$CIRCLE_BUILD_NUM" --baseURL=https://$HEROKU_APP_NAME_STAGING.herokuapp.com --savePath=results.xml --errorOnFailure=100
      
      - store_test_results:
          path: ~/project/build/launchready/results.xml
      - store_artifacts:
          path: ~/project/build/launchready/results.xml

  deploy-production:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      # - add-ssh-keys:
      #     fingerprints:
      #       - "81:c8:44:89:af:ef:08:f3:4b:a7:85:77:ae:38:bd:50"

      # - run:
      #     name: Deploy Master to Heroku
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         # Heroku's fingerprint
      #         echo 'heroku.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==' >> ~/.ssh/known_hosts

      #         # Push changes
      #         git push --force git@heroku.com:$HEROKU_APP_NAME_PRODUCTION.git HEAD:refs/heads/master
      #       fi

workflows:
  version: 2
  do-the-things:
    jobs:
      - ci:
          filters: 
            branches:
              only: master
      - deploy-staging:
          requires: 
            - ci
      - test-staging:
          requires:
            - deploy-staging
      - human-staging:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - test-staging
            - human-staging